1710-capstone-521ATE/capstone

server-heroku/api/index.js, server-heroku/api/users.js, server-heroku/app.js, server-heroku/package-lock.json
=> added koa-router and one get users route

server-heroku/api/users.js, server-heroku/app.js, server-heroku/package.json
Feature: Harry Henderson
Added: User GET/PUT/POST/DELETE routes
all usable by ID
-JI
=> user routes largely complete

client-react-native/App.js, client-react-native/components/SignUpForm.js, client-react-native/store/index.js, client-react-native/store/reducers/User.js
Added user reducer
Initialized store
Initialized provider
Connected SignUp form
=> i am the git scrub

client-react-native/App.js
=> map header title changed

server-heroku/.gitignore, server-heroku/api/restaurants.js, server-heroku/app.js
created secret.js, put it into .gitignore, and updates restaurant.js with new secret yelp key.
=> shhh its a secret

server-heroku/api/restaurants.js
=> update with new secrets

.expo/packager-info.json, .expo/settings.json, client-react-native/Utils/location.js, client-react-native/components/AddUsers.js, client-react-native/components/MapTemp.js, client-react-native/package.json, client-react-native/socket.js, client-react-native/store/reducers/Event.js, client-react-native/store/reducers/Users.js, server-heroku/socket/index.js
=> Event creator

.expo/packager-info.json, .expo/settings.json
=> deleted expo

client-react-native/components/AddUsers.js, client-react-native/socket.js, server-heroku/api/groups.js
=> Otherrefactor

client-react-native/components/AddUsers.js, client-react-native/components/EventView.js, client-react-native/store/reducers/Users.js, server-heroku/package-lock.json, server-heroku/socket/index.js
=> Join room hookup

client-react-native/components/WaitingRoom.js, client-react-native/components/YelpChoices.js
restaurant list renders onto waiting room.
=> Render restaurants

client-react-native/App.js, client-react-native/components/Login.js, client-react-native/components/Map.js, client-react-native/store/index.js, server-heroku/api/users.js
Combined viewing users and viewing restaurants on map, and swapping status - all live
=> Livemapview

client-react-native/components/YelpChoices.js
button change implementation still needs to get worked in
=> Buttonchange

client-react-native/App.js, client-react-native/components/EventView.js
See above. The Back Button is no more in the appropriate places.
Scroll view is enacted on event view. Hooray!
=> back button murdered and scroll has risen

client-react-native/components/EventView.js
Introduced Scroll View Updating
=> scroll update for events

client-react-native/components/AddUsers.js, client-react-native/package.json
AddUsers button is now rounded.
=> Add users style

client-react-native/components/EventView.js
CHANGED: Moved Create Event button below existent events for better user flow
REMOVED: Input field and button for manual event joining. No longer necessary.
=> moved buttons, murdered input

client-react-native/components/AddUsers.js, client-react-native/components/EventView.js, client-react-native/store/reducers/Users.js
=> event naming works

server-heroku/api/groups.js, server-heroku/db/models/event.js, server-heroku/seed.js
=> backend stuff for previous PR

client-react-native/App.js
Disabled three finger swipe on components that have had back button removed.
FEATURE: NO WAY OUT.
=> disabled certain gestures

client-react-native/components/AddUsers.js
styled input form in addusers component!
=> input form in add users styled for now

client-react-native/components/AddUsers.js, server-heroku/db/models/user.js, server-heroku/utils/groupPut.js
=> Friend search

client-react-native/components/LoginForm.js
front end validation merged with master
=> Front end validation

client-react-native/components/AddUsers.js, client-react-native/components/EventView.js, client-react-native/components/FinalDestination.js, client-react-native/components/Login.js, client-react-native/components/LoginForm.js, client-react-native/store/reducers/Event.js, client-react-native/store/reducers/User.js, server-heroku/api/users.test.js, server-heroku/app.js, server-heroku/auth/index.js
Adjusted error handling to pass error message to the front end to display for log in validation.
Added extra tests to the /api/users route.
Cleaned up a little bit of the FE code.
=> Error handling

client-react-native/Utils/restaurantAPI.js
500m radius introduced to API search! Hooraaaaay!
=> Api radius

client-react-native/Utils/restaurantAPI.js
=> reduced radius to 250m

client-react-native/App.js, client-react-native/components/HomeButton.js
=> Home button

server-heroku/api/groups.js, server-heroku/socket/index.js, server-heroku/utils/groupPut.js
deleted commented/deprecated code
=> backend cleanup

client-react-native/App.js, client-react-native/app.json, client-react-native/components/AddUsers.js, client-react-native/components/EventView.js, client-react-native/components/FinalDestination.js, client-react-native/components/HomeButton.js, client-react-native/components/LogOutButton.js, client-react-native/components/MapTemp.js, client-react-native/components/ResultView.js, client-react-native/components/WaitingRoom.js, client-react-native/components/YelpChoices.js, server-heroku/.expo/packager-info.json, server-heroku/.expo/settings.json
=> Style update

client-react-native/components/SignUpForm.js, client-react-native/components/YelpChoices.js, client-react-native/socket.js, server-heroku/socket/index.js
Added manual override for waiting on users to respond.
=> Manual override

client-react-native/components/LoginForm.js, client-react-native/components/SignUpForm.js
=> Signup style

client-react-native/components/FinalDestination.js, server-heroku/.expo/packager-info.json, server-heroku/.expo/settings.json, server-heroku/api/index.js, server-heroku/api/transit.js
Fixed FE call for transit time. Please merge!
=> Transit time api
